controllers/SiteController.php
<?php
namespace app\controllers;
 
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\data\Pagination;
use app\models\ContactForm;
use app\models\LoginForm;
use app\models\ConfirmEmailForm;
use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\SignUpForm;
use app\models\Users;
use app\models\Crosswords;
use app\models\Categories;
use app\models\Contact;
use app\models\DiscussionTexts;
use app\models\Posts;
use yii\helpers\Url;
use app\models\Notifications;
use Yii;

 
class SiteController extends AppController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),        
                'rules' => [
                    [
                        'actions' => ['error', 'index', 'login', 'signup', 
                            'confirm-email', 'request-password-reset', 'reset-password', 'search',
                            'error', 'contact-us', 'captcha', 'about', 'faq', 'privacy-policy', 'games', 'leaderboard',
                            'how-to-use', 'other', 'blog', 'problem', 'discussions', 'post', 'championship'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],                    
                    [
                        'actions' => ['error', 'index', 'logout', 'error', 'contact-us', 'search',
                            'captcha', 'about', 'faq', 'privacy-policy', 'games', 'leaderboard', 
                            'how-to-use', 'other', 'blog', 'problem', 'discussions', 
                            'add-discussion', 'delete-discussion', 'post', 'championship'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'denyCallback'  => function ($rule, $action) {
                     return $this->redirect($this->prefix_language.'/site/errorPage');
                },
            ]
        ];
    }

    public $socialData = [];
 
    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'foreColor' => 0xf7931e,                
//                'fixedVerifyCode' => $this->generateCaptcha(),
            ],
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    
    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception, 'language' => $this->language_view]);
        }
    }
    
    public function actionGames()
    {
        return $this->render('games'.$this->language_view);
    }

    public function actionOther()
    {
        return $this->render('other'.$this->language_view);
    }

    public function actionBlog()
    {
        $limit = Yii::$app->request->get('per-page',10);
        $offset = (Yii::$app->request->get('page', 1)-1)*$limit;
        
        $conditions = '';

        $posts = new Posts();

        $result = $posts->getPosts($limit, $offset, $conditions);

        $posts = $result['posts'];

        $pages = new Pagination();
        $pages->totalCount = $result['count'];
        $pages->setPageSize('10');

        $this->socialData = [
        'description' => $this->getSocialData('006'),
        'keywords' => 'crossword.am online-crossword, armenian crossword, victorina, armenian victorina, հայկական վիկտորինա, խաչբառ, օնլայն, հայկական, բլոգ, blog, տեղեկատվություն, հետաքրքիր', 
        'image' => '/images/blog-image.jpg'];

        return $this->render('blog'.$this->language_view, ['posts' => $posts, 'pages' => $pages]);
    }

    public function actionLeaderboard()
    {
        $leaders = new Users();
        $leaders = $leaders->getLeaders();

        return $this->render('leaderboard'.$this->language_view, ['leaders' => $leaders]);
    }

    public function actionHowToUse()
    {
        return $this->render('howtouse'.$this->language_view);
    }    
    
    public function actionAbout() 
    {
        $limit = Yii::$app->request->get('per-page',20);
        $offset = (Yii::$app->request->get('page', 1)-1)*$limit;
                
        $contacts = array();
        
        $result = new Contact();
        $result = $result->getPublicContacts($limit, $offset);
        
        $contacts = $result['contacts'];
        
        $pages = new Pagination();                   
        $pages->totalCount = $result['count'];
        $pages->setPageSize('20');        
                
        return $this->render('about'.$this->language_view, ['contacts' => $contacts, 'pages' => $pages]);
    }
    
    public function actionFaq() 
    {
        return $this->render('faq'.$this->language_view);
    }
 
    public function actionPrivacyPolicy() 
    {
        return $this->render('policy'.$this->language_view);
    }

    public function actionContactUs()
    {
        $model = new ContactForm();
        if (!Yii::$app->user->isGuest) {
            $model->email = Yii::$app->user->identity->attributes['email'];
            $model->name = Yii::$app->user->identity->attributes['first_name'] . ' ' . Yii::$app->user->identity->attributes['last_name'];
        }
        
        if ($model->load(Yii::$app->request->post()) && $model->contact()) {
            $this->alert('success', $this->getAlertMessage('003'));
            return $this->refresh();
        }
                
        return $this->render('contact'.$this->language_view, [
            'model' => $model,
        ]);
    }

    public function actionChampionship()
    {
        return $this->render('championship'.$this->language_view);
    }

    public function actionSearch($id)
    {
        $results = [];
        $key = strip_tags($id);
        if($key) {
            $keys = explode(' ', $key);
            $crossword = '';
            $post = '';
            $quiz = '';
            if(!empty($keys)) {
                foreach ($keys as $key) {
                    if($crossword == '') {
                        $crossword = '(crosswords.crossword_name LIKE "%'.$key.'%" OR crosswords.category LIKE "%'.$key.'%"';
                    } else {
                        $crossword = $crossword.' OR crosswords.crossword_name LIKE "%'.$key.'%" OR crosswords.category LIKE "%'.$key.'%"';
                    }
                    if($post == '') {
                        $post = '(posts.title LIKE "%'.$key.'%" OR posts.keywords LIKE "%'.$key.'%"';
                    } else {
                        $post = $post.' OR posts.title LIKE "%'.$key.'%" OR posts.keywords LIKE "%'.$key.'%"';
                    }
                    if($quiz == '') {
                        $quiz = '(categories.category_name LIKE "%'.$key.'%" OR categories.keywords LIKE "%'.$key.'%"';
                    } else {
                        $quiz = $quiz.' OR categories.category_name LIKE "%'.$key.'%" OR categories.keywords LIKE "%'.$key.'%"';
                    }
                }
                $post = $post.')';
                $crossword = $crossword.')';
                $quiz = $quiz.')';
                $posts = new Posts();
                $posts = $posts->search($post);
                $crosswords = new Crosswords();
                $crosswords = $crosswords->search($crossword);
                $categories = new Categories();
                $categories = $categories->search($quiz);
                if(!empty($posts)) {
                    foreach ($posts as $post) {
                        $results[] = [
                            'type' => 'post',
                            'id' => $post['id'],
                            'title' => $post['title'],
                            'image' => $post['image'],
                        ];
                    }
                }
                if(!empty($crosswords)) {
                    foreach ($crosswords as $crossword) {
                        $results[] = [
                            'type' => 'crossword',
                            'id' => $crossword['id'],
                            'title' => $crossword['crossword_name'],
                            'image' => $crossword['image'],
                        ];
                    }   
                }
                if(!empty($categories)) {
                    foreach ($categories as $category) {
                        $results[] = [
                            'type' => 'quiz',
                            'id' => $category['id'],
                            'title' => $category['category_name'],
                            'image' => $category['image'],
                        ];
                    }   
                }
            } else {
                return $this->redirect($this->prefix_language.'/site/index');    
            }
        } else {
            return $this->redirect($this->prefix_language.'/site/index');
        }
        return $this->render('search'.$this->language_view, ['results' => $results]);
    }
    
    public function actionIndex() 
    {
        $this->socialData = [
        'description' => $this->getSocialData('007'),
        'keywords' => 'crossword.am online-crossword, armenian crossword, victorina, armenian victorina, հայկական վիկտորինա, խաչբառ, օնլայն, հայկական, crossword.am գլխավոր էջ, հայկական խաչբառեր, օնլայն խաղեր',
        'image' => '/images/main-image.jpg'];
        return $this->render('index'.$this->language_view);
    }
 
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect($this->prefix_language.'/site/index');
        }
 
        $model = new LoginForm();
        
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
$this->title="Crossword.am | Կապ";
?>
<div class="container">
    <h1 class="mainPageTitle blackPageTitle">#կապ մեզ հետ</h1>
    <div class="box">
      <div class="contactCover">

      </div>
      <div class="contactInfo">
        <ul>
          <li class="contactItem email" title="էլ հասցե">
            info@crossword.am
          </li>
          <li class="contactItem location" title="բնակավայր">
            Yerevan, Armenia        
          </li>
          <li class="contactItem mobile" title="հեռախոս">
            +374(77)590-123
          </li>
        </ul>
      </div>
      <div class="contactForm">
        <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
              <div class="formRow">
                  <?php echo $form->field($model, 'name'); ?>
              </div>
              <div class="formRow">
                  <?php echo $form->field($model, 'email'); ?>
              </div>
              <div class="formRow">
                  <?php echo $form->field($model, 'message')->textArea(['rows' => 3]); ?>
              </div>
              <div class="formRow">
                  <?php echo $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                      'template' => '<div class="captchaImage">{image}</div><div class="captchainput">{input}</div>',
                  ]); ?>
              </div>
              <div class="submitSect">
                  <?php echo Html::submitButton('Ուղարկել', ['class' => 'borderBtn orangeBorderBtn', 'name' => 'contact-button']); ?>
              </div>
      </div>
      <div class="clear">
      </div>
   </div>
   <div class="box">
        <div class="mainCity" data-url="/city/list">
            <h1>#քաղաքներ</h1>
            <p>քաղաք - քաղաք</p>
        </div>
    </div>
   <div class="box">
        <div class="mainFb" data-url="https://www.facebook.com/crossword.am">
            <h1>facebook</h1>
            <p>միացեք մեզ ֆեյսբուքում</p>
        </div>
    </div>
    <div class="box">
        <div class="mainDisc" data-url="/site/discussions">
            <h1>քննարկումներ</h1>
            <p>մասնակցեք մեր քննարկումներին</p>
        </div>
    </div>
    <div class="box">
        <div class="mainBlog" data-url="/site/blog">
            <h1>բլոգ</h1>
            <p>հետաքրքիր տեղեկատվություն</p>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){       
       $('#contactform-verifycode-image ').click(function() {
         src = $('#contactform-verifycode-image ').attr('src');
          // check for existing ? and remove if found
         queryPos = src.indexOf('?');
         if(queryPos != -1) {
            src = src.substring(0, queryPos);
         }    
         $('#contactform-verifycode-image').attr('src', src + '?' + Math.random());
         return false;
      });
    });
</script>

views/site/discussions.php
<?php

$this->title="Crossword.am | Քննարկումներ";

?>
<div class="container">
    <h1 class="mainPageTitle blackPageTitle">#քննարկումներ</h1>
    <div class="box">
    	<?php if(!empty($discussions)) { ?>
    	<ul>
    		<?php foreach($discussions as $d) { ?>
    		<li class="discussions">
    			<a href="/site/discussions?id=<?php echo $d['id'];?>"><?php echo $d['name']; ?> - (<?php echo $d['count']; ?>)</a>
    		</li>
    		<?php } ?>
    	</ul>
    	<?php } else { ?>
    	<h4 class="noInfSt">
    		քննարկումներ չկան
    	</h4>
    	<?php } ?>
    </div>
    <?php echo $this->renderFile($this->findViewFile('contactButtons')); ?>   
    <div class="box">
        <div class="mainFb" data-url="https://www.facebook.com/crossword.am">
            <h1>facebook</h1>
            <p>միացեք մեզ ֆեյսբուքում</p>
        </div>
    </div>
    <div class="box">
        <div class="mainGamesBox" data-url="/site/games">
            <h1>խաղեր</h1>
            <p>մեր խաղերը</p>
        </div>
    </div>
    <div class="box">
        <div class="mainBlog" data-url="/site/blog">
            <h1>բլոգ</h1>
            <p>հետաքրքիր տեղեկատվություն</p>
        </div>
    </div>
</div>

views/site/discussions_en.php
<?php

$this->title="Crossword.am | Discussions";

?>
<div class="container">
    <h1 class="mainPageTitle blackPageTitle">#discussions</h1>
    <div class="box">
    	<?php if(!empty($discussions)) { ?>
    	<ul>
    		<?php foreach($discussions as $d) { ?>
    		<li class="discussions">
    			<a href="/en/site/discussions?id=<?php echo $d['id'];?>"><?php echo $d['name']; ?> - (<?php echo $d['count']; ?>)</a>
    		</li>
    		<?php } ?>
    	</ul>
    	<?php } else { ?>
    	<h4 class="noInfSt">
    		no discussions
    	</h4>
    	<?php } ?>
    </div>
    <?php echo $this->renderFile($this->findViewFile('contactButtons_en')); ?>   
    <div class="box">
        <div class="mainLeaders" data-url="/en/site/leaderboard">
            <h1>leaders</h1>
            <p>get points and be on top</p>
        </div>
    </div>
    <div class="box">
        <div class="mainDisc" data-url="/en/site/discussions">
            <h1>discussions</h1>
            <p>participation in our discussions</p>
        </div>
    </div>
    <div class="box">
        <div class="mainFb" data-url="https://www.facebook.com/crossword.am">
            <h1>facebook</h1>
            <p>find us on facebook</p>
        </div>
    </div>
</div>

views/site/discussions_ru.php
<?php

$this->title="Crossword.am | Обсуждения";

?>
<div class="container">
    <h1 class="mainPageTitle blackPageTitle">#обсуждения</h1>
    <div class="box">
    	<?php if(!empty($discussions)) { ?>
    	<ul>
    		<?php foreach($discussions as $d) { ?>
    		<li class="discussions">
    			<a href="/ru/site/discussions?id=<?php echo $d['id'];?>"><?php echo $d['name']; ?> - (<?php echo $d['count']; ?>)</a>
    		</li>
    		<?php } ?>
    	</ul>
    	<?php } else { ?>
    	<h4 class="noInfSt">
    		нет обсуждений
    	</h4>
    	<?php } ?>
    </div>
    <?php echo $this->renderFile($this->findViewFile('contactButtons_ru')); ?>   
    <div class="box">
        <div class="mainLeaders" data-url="/ru/site/leaderboard">
            <h1>лидеры</h1>
            <p>получайте очки и поднимайтесь в топе</p>
        </div>
    </div>
    <div class="box">
        <div class="mainDisc" data-url="/ru/site/discussions">
            <h1>обсуждения</h1>
            <p>участвуйте в обсуждениях</p>
        </div>
    </div>
    <div class="box">
        <div class="mainFb" data-url="https://www.facebook.com/crossword.am">
            <h1>facebook</h1>
            <p>мы в фейсбуке</p>
        </div>
    </div>
</div>

views/site/error.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */
if(strpos(Url::current(), '?language=en')) {
$this->title = '404 error | page not found';
?>
<div class="container">
    <h1 class="mainPageTitle blackPageTitle">#404 error</h1>
    <div class="box">
        <h1 class="error404Title">#404 error</h1>
        <p class="error404Message">
            page does not exists or you do not have permission to access this page։
        </p>
    </div>
    <?php echo $this->renderFile($this->findViewFile('contactButtons_en')); ?>   
    <div class="box">
        <div class="mainLeaders" data-url="/en/site/leaderboard">
            <h1>leaders</h1>
            <p>get points and be on top</p>
        </div>
    </div>
    <div class="box">
        <div class="mainDisc" data-url="/en/site/discussions">
            <h1>discussions</h1>
            <p>participation in our discussions</p>
        </div>
    </div>
    <div class="box">
        <div class="mainFb" data-url="https://www.facebook.com/crossword.am">
            <h1>facebook</h1>
            <p>find us on facebook</p>
        </div>
    </div>
</div>
<?php } else if(strpos(Url::current(), '?language=ru')) {
$this->title = '404 ошибка | страница не существует';
?>
<div class="container">
    <h1 class="mainPageTitle blackPageTitle">#404 ошибка</h1>
    <div class="box">
        <h1 class="error404Title">#404 ошибка</h1>
        <p class="error404Message">
            страница которую вы ищите не существует։
        </p>
    </div>
    <?php echo $this->renderFile($this->findViewFile('contactButtons_ru')); ?>   
    <div class="box">
        <div class="mainLeaders" data-url="/ru/site/leaderboard">
            <h1>лидеры</h1>
            <p>получайте очки и поднимайтесь в топе</p>
        </div>
    </div>
    <div class="box">
        <div class="mainDisc" data-url="/ru/site/discussions">
            <h1>обсуждения</h1>
            <p>участвуйте в обсуждениях</p>
        </div>
    </div>
    <div class="box">
        <div class="mainFb" data-url="https://www.facebook.com/crossword.am">
            <h1>facebook</h1>
            <p>мы в фейсбуке</p>
        </div>
    </div>
</div>
<?php } else {

$this->title = '404 սխալ | էջը գոյություն չունի';
?>
<div class="container">
    <h1 class="mainPageTitle blackPageTitle">#404 սխալ</h1>
    <div class="box">
        <h1 class="error404Title">#404 սխալ</h1>
        <p class="error404Message">
            էջը, որը դուք փնտրում եք գոյություն չունի, կամ դուք չունենք թույլտվություւն դիմելու այս էջին։
        </p>
    </div>
    <?php echo $this->renderFile($this->findViewFile('contactButtons')); ?>   
    <div class="box">
        <div class="mainLeaders" data-url="/site/leaderboard">
            <h1>առաջատարներ</h1>
            <p>կուտակեք միավորներ և լրացրեք առաջատարների շարքերը</p>
        </div>
    </div>
    <div class="box">
        <div class="mainFb" data-url="https://www.facebook.com/crossword.am">
            <h1>facebook</h1>
            <p>միացեք մեզ ֆեյսբուքում</p>
        </div>
    </div>
    <div class="box">
        <div class="mainDisc" data-url="/site/discussions">
            <h1>քննարկումներ</h1>
            <p>մասնակցեք մեր քննարկումներին</p>
        </div>
    </div>
    <div class="box">
        <div class="mainBlog" data-url="/site/blog">
            <h1>բլոգ</h1>
            <p>հետաքրքիր տեղեկատվություն</p>
        </div>
    </div>
</div>
<?php } ?>
<div class="error404Popup"></div>
<script type="text/javascript">    

    $(document).ready(function(){
        $('.error404Popup').show();

        $('.error404Popup').on('mousemove', function( event ){
                var x = event.pageX-1500;
                var y = event.pageY-1500;
                $('.error404Popup').css('background-position', x+'px '+y+'px');
        });

        $('.error404Popup').on('click', function()
        {
            $(this).fadeOut('200');
        });
    });
</script>

views/site/other.php
<?php

use yii\widgets\LinkPager;
$this->title="Crossword.am | Այլ";
?>
<div class="container">
    <h1 class="mainPageTitle blackPageTitle">#այլ խաղեր</h1>
    <div class="box">
        <h1 class="commingSoon">#շուտով</h1>
    </div>
    <?php echo $this->renderFile($this->findViewFile('contactButtons')); ?>   
    <div class="box">
        <div class="mainFb" data-url="https://www.facebook.com/crossword.am">
            <h1>facebook</h1>
            <p>միացեք մեզ ֆեյսբուքում</p>
        </div>
    </div>
    <div class="box">
        <div class="mainDisc" data-url="/site/discussions">
            <h1>քննարկումներ</h1>
            <p>մասնակցեք մեր քննարկումներին</p>
        </div>
    </div>
    <div class="box">
        <div class="mainBlog" data-url="/site/blog">
            <h1>բլոգ</h1>
            <p>հետաքրքիր տեղեկատվություն</p>
        </div>
    </div>
</div>

views/site/signup.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
$this->title="Crossword.am | Գրանցում";
?>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script> 
<div class="container">
    <h1 class="mainPageTitle blackPageTitle">#գրանցում</h1>
    <div class="box">
            <h1 class="aboutSignUp">#մի փոքր գրանցման մասին...</h1>
            <div class="aboutSignUpText">այն ձեզ բազմաթիվ առավելություններ և տալիս սովորական այցելուների նկատմամբ։ գրանցված խաղացողներն ունեն իրենց անհատական էջերը, պահպանում են իրենց արդյունքները և մասնակցում են մեկնաբանություններին։ խորհուրդ է տրվում օգտագործել իրական տվյալներ գրանցման ժամանակ հետագայում խնդիրներից խուսափելու նպատակով։
            </div>
            <?php $form = ActiveForm::begin([
            'id' => 'signupform', 
            'action' => '/site/signup',
            'fieldConfig' => [
                'template' => '{label}{input}<p class="help-block"></p>'
                ],
            ]); ?>                    
            <div class="formRow twoCol">
                <?php echo $form->field($signup, 'username')->textInput(); ?>
                <?php echo $form->field($signup, 'email')->textInput(); ?>
            </div>
            <div class="formRow twoCol">
                <?php echo $form->field($signup, 'password')->passwordInput(); ?>
                <?php echo $form->field($signup, 'password_repeat')->passwordInput(); ?>
            </div>
            <div class="formRow twoCol">
                <?php echo $form->field($signup, 'first_name')->textInput(); ?>
                <?php echo $form->field($signup, 'last_name')->textInput(); ?>
            </div>
            <div class="formRow twoCol">
                <?php echo $form->field($signup, 'address')->textInput(); ?>
                <?php echo $form->field($signup, 'city', ['inputOptions' => ['id' => 'city']])->hiddenInput()->label(false); ?>
                <?php echo $form->field($signup, 'country', ['inputOptions' => ['id' => 'country']])->hiddenInput()->label(false); ?>
                <?php echo $form->field($signup, 'street', ['inputOptions' => ['id' => 'street']])->hiddenInput()->label(false); ?>
                <?php echo $form->field($signup, 'state', ['inputOptions' => ['id' => 'state']])->hiddenInput()->label(false); ?>
                <?php echo $form->field($signup, 'zip_code', ['inputOptions' => ['id' => 'zip_code']])->hiddenInput()->label(false); ?>
                <?php echo $form->field($signup, 'lat_lng', ['inputOptions' => ['id' => 'lat_lng']])->hiddenInput()->label(false); ?>
            </div>
            <div class="formRow twoCol">
                    <?php $ages = array(); ?>
                    <?php 
                    for($i=7; $i<=90; $i++) { 
                        $ages[$i] = $i;
                    } ?>
                    <?php
                    echo $form->field($signup, 'age')->dropDownList(
                            $ages, ['prompt'=>'#տարիք'])->label(false);
                    echo $form->field($signup, 'sex')->radioList(array('boy'=>'#արական','girl'=>'#իգական')); 
                    ?>
            </div>
            <div class="clear"></div>
            <?php echo $form->field($signup, 'facebook_id')->hiddenInput()->label(false); ?>
            <div class="submitSect">
                <?php echo Html::submitButton('Գրանցվել', ['class' => 'borderBtn orangeBorderBtn', 'name' => 'signup-button']); ?>
            </div>
            <div class="alreadyMember">
              #արդեն գրանցված եք? <a href="#loginPopup" class="standartBtn orangeBtn mgnPopupBtn">Մուտք</a>
            </div>
            <div class="clear"></div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
    <div class="box">
        <div class="mainLeaders" data-url="/site/leaderboard">
            <h1>առաջատարներ</h1>
            <p>կուտակեք միավորներ և լրացրեք առաջատարների շարքերը</p>
        </div>
    </div>
    <div class="box">
        <div class="mainFb" data-url="https://www.facebook.com/crossword.am">
            <h1>facebook</h1>
            <p>միացեք մեզ ֆեյսբուքում</p>
        </div>
    </div>
    <div class="box">
        <div class="mainDisc" data-url="/site/discussions">
            <h1>քննարկումներ</h1>
            <p>մասնակցեք մեր քննարկումներին</p>
        </div>
    </div>
    <div class="box">
        <div class="mainBlog" data-url="/site/blog">
            <h1>բլոգ</h1>
            <p>հետաքրքիր տեղեկատվություն</p>
        </div>
    </div>
<script>

$(document).ready(function(){
  $('.aboutSignUp').on('click', function()
  {
    $('.aboutSignUpText').slideToggle('500', function(){

    });
  });
});

var autocomplete;
var componentForm = {
  street_number: 'short_name',
  route: 'long_name',
  locality: 'long_name',
  administrative_area_level_1: 'short_name',
  country: 'long_name',
  postal_code: 'short_name'
};


function initialize() {
    
    

   autocomplete = new google.maps.places.Autocomplete(
                (document.getElementById('signupform-address')),
                {types: ['geocode'],
        });
        
        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            fillInAddress();
        });
 
}

google.maps.event.addDomListener(window, 'load', initialize);


function getLatLngFromAddress(address) {
           var geocoder = new google.maps.Geocoder();
           geocoder.geocode({'address': address}, function(results, status) {
               if (status == google.maps.GeocoderStatus.OK) {
                   $('#lat_lng').val(results[0].geometry.location.lat()+','+results[0].geometry.location.lng())                   
               } else {
                   console.log("Geocode was not successful for the following reason: " + status);
               }
           });
       }

       function fillInAddress() {
           
            $("#city").val('');
            $("#street").val('');
            $("#country").val('');
            $("#zip_code").val('');
            $("#state").val('');
            $("#street").val('');
           // Get the place details from the autocomplete object.
           var place = autocomplete.getPlace();
           for (var component in componentForm) {
               if (document.getElementById(component)) {
                   document.getElementById(component).value = '';
                   document.getElementById(component).disabled = false;
               }

           }

           // Get each component of the address from the place details
           // and fill the corresponding field on the form.
           var address = '';
           var city="";
           for (var i = 0; i < place.address_components.length; i++) {
               var addressType = place.address_components[i].types[0];

               if (componentForm[addressType]) {
                   var val = place.address_components[i][componentForm[addressType]];
                   if (addressType === "locality") {
                    $("#city").val(val);
                   }                   
                   if (addressType === "street_number") {
                    $("#street").val(val);
                   }
                   if (addressType === "administrative_area_level_1") {
                    $("#state").val(val);
                   }                    
                   
                    if (addressType === "country") {
                    $("#country").val(val);
                   }
                    if (addressType === "postal_code") {
                    $("#zip_code").val(val);
                   }                             
                   address = address + ' ' + val;
                  
                   if (document.getElementById(addressType)) {
                       document.getElementById(addressType).value = val;
                   }
               }
           }
           getLatLngFromAddress(address);
       }
</script>